# Generated by Django 3.0.4 on 2020-03-16 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='annual_statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateTimeField()),
                ('value', models.CharField(max_length=255)),
                ('name_currency2', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Main.currency')),
            ],
        ),
    ]
