# Generated by Django 3.0.4 on 2020-03-16 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_annual_statistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annual_statistics',
            name='name_currency2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.currency'),
        ),
    ]
