# Generated by Django 3.0.4 on 2020-03-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_auto_20200316_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='statistics_users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statistics_user', models.CharField(max_length=255, verbose_name='users')),
                ('name_user', models.CharField(max_length=255, verbose_name='name users')),
            ],
            options={
                'ordering': ['statistics_user'],
                'abstract': False,
            },
        ),
    ]
