# Generated by Django 3.0.4 on 2020-03-17 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_statistics_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statistics_users',
            options={},
        ),
    ]
